### ISSUE TITLE
The number of genotype hiddens should be the same number of PCA's n components?

### ISSUE THREAD

**Issue by inoue0426** [aksinghal5590/rlipp#2]
Hi @aksinghal5590 

When I run your code, I got the below error.

```console
"""
Traceback (most recent call last):
  File "python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "python3.9/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "python3.9/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "python3.9/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/inoue019/code/rlipp/src/rlipp_calculator.py", line 146, in calc_term_rlipp
    p_rho, p_pval = self.exec_lm(X_parent, y)
  File "/home/inoue019/code/rlipp/src/rlipp_calculator.py", line 132, in exec_lm
    X_pca = pca.fit_transform(X)
  File "python3.9/site-packages/sklearn/decomposition/_pca.py", line 433, in fit_transform
    U, S, Vt = self._fit(X)                                                                                                        m
  File "python3.9/site-packages/sklearn/decomposition/_pca.py", line 483, in _fit
    return self._fit_full(X, n_components)
  File "python3.9/site-packages/sklearn/decomposition/_pca.py", line 501, in _fit_full
    raise ValueError(
ValueError: n_components=6 must be between 0 and min(n_samples, n_features)=4 with svd_solver='full'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/inoue019/code/rlipp/src/rlipp_helper.py", line 27, in <module>
    main()
  File "/home/inoue019/code/rlipp/src/rlipp_helper.py", line 23, in main
    rlipp_calculator.calc_scores()
  File "/home/inoue019/code/rlipp/src/rlipp_calculator.py", line 170, in calc_scores
    rlipp_results = parallel(delayed(self.calc_term_rlipp)(feature_map[term], child_feature_map[term], drug_pos_map[drug], term, drug) for term in self.terms)                                                                                                        ug) for term in self.terms)
  File "python3.9/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "python3.9/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: n_components=6 must be between 0 and min(n_samples, n_features)=4 with svd_solver='full'
```

This is my rlipp.sh.

```sh
#!/bin/bash

homedir='../DrugCell/data/'
ontology="${homedir}drugcell_ont.txt"
gene2idfile="${homedir}gene2ind.txt"
cell2idfile="${homedir}cell2ind.txt"
cell_mutation="${homedir}cell2mutation.txt"
test="${homedir}test_rcell_over50_not_equal.txt"

modeldir='inoue019/'
predicted="${modeldir}Result_157/drugcell.predict"
output="${modeldir}/rlipp.out"
hidden="${modeldir}Hidden_157"

cpu_count=30

neurons=6

python -u /home/inoue019/code/rlipp/src/rlipp_helper.py -hidden $hidden -ontology $ontology -test $test  \
	-gene2idfile $gene2idfile -cell2idfile $cell2idfile -cell_mutation $cell_mutation -output $output \
	-predicted $predicted -cpu_count $cpu_count -drug_count 0 -genotype_hiddens $neurons > "${modeldir}/rlipp.log"

```

---

From my understanding, the number of genotype hiddens is used for getting hidden weight for each GO and n_components of PCA. And this can make the error because the number of weight and n_compornents can be the same. Could you give me the advice to deal with this?

https://github.com/aksinghal5590/rlipp/blob/7056293809c3a088126b84df5429716ca8b60ba4/src/rlipp_calculator.py#L81-L137

**Comment by aksinghal5590** [comment]
n_components can be equal to the number of features (number of genotype hiddens). I think the problem is in the number of samples. It should be more than n_components.
If you continue to face this issue, you can remove PCA.

**Comment by inoue0426** [comment]
Sounds good! I'll try to do that without PCA :)
